### ISSUE TITLE
Use Polkit to limit process EUID elevations

### ISSUE THREAD

**Issue by ikeydoherty** [PandaHugMonster/LittleServerExecuter#2]
Context: https://plus.google.com/u/0/+%D0%98%D0%B2%D0%B0%D0%BD%D0%9F%D0%BE%D0%BD%D0%BE%D0%BC%D0%B0%D1%80%D0%B5%D0%B2/posts/KrhrmmFYZi8

Use Polkit to build an API to abstract the systemd DBUS API - and don't be root all the time.

Or: lazy route. Require pkexec to launch, provide the appropriate file :P

**Comment by PandaHugMonster** [comment]
Thank you for the ticket! Problem has been solved, from version 0.4.4 Authorization is used through Polkit + DBus.
Thank you!

**Comment by ikeydoherty** [comment]
Nice :)

**Comment by PandaHugMonster** [comment]
Your links really helped me! Thank you! Will have more suggestions in future, please feel free to post them!!! :)
